apiVersion: apps/v1
kind: Deployment
metadata:
  name: prt-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prt-web
  template:
    metadata:
      labels:
        app: prt-web
    spec:
      containers:
        - name: prt-web
          image: rajugayen/prt-cicd:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
