[ci_master]
54.164.50.230 ansible_ssh_private_key_file=/home/ubuntu/.ssh/key.pem ansible_user=ubuntu
[ci_agent]
3.235.232.58 ansible_ssh_private_key_file=/home/ubuntu/.ssh/key.pem ansible_user=ubuntu
